### ISSUE TITLE
aliens vs predator has no sound (works in PIFBA)

### ISSUE THREAD

**Issue by objectchris** [libretro/fba-libretro#47]
Hi :) Seems like Aliens Vs Predator has sound issues in FBA-libretro. Strangely, the same rom works on the PIFBA emulator with sound working.

Rom is "avsp.zip" which is the "Euro 94052" version

**Comment by Oggom** [comment]
It's working fine on Windows at least, the problem might be hardware specific.

**Comment by dankcushions** [comment]
Interesting! I'm using a Raspberry Pi 2 (with Retroarch 1.2).

**Comment by darksaviorx** [comment]
Sound works for me. I'm using a Pi 2 with Retroarch 1.2.2

**Comment by objectchris** [comment]
me to now! i don't get any sound during the attract mode but as soon as I'm in the game it's fine. I'm sure this is different from pre Retroarch 1.2.2, but also I'm not sure why the retroarch version would matter! anyway, can close :)
